import React, {Component} from 'react';
import DataStructure from './DataStructure';
const dataUsers = [
  {
      "NOMBRE":"RAMON",
      "COMUNA":"MAIPU",
      "REGION":"METROPOLITANA",
      "FECHA_NACIMIENTO":"1994/07/07",
      "DESDE_DONDE_QUIERE_CONOCER": "9",
      "HASTA_DONDE_QUIERE_CONOCER": "12",
      "SEXO": "M",
      "EL_GRUPO_QUE_QUIERE_SOLO_HOMBRES_MUJERES_O_MIXTO": "MIXTO",
      "RANGO_DE_EDAD_QUE_DESEA_ENCONTRAR_COMPANEROS_MIN": "18",
      "RANGO_DE_EDAD_QUE_DESEA_ENCONTRAR_COMPANEROS_MAX": "30",
      "SOLO_CARPA_HOSTAL_HOTEL_O_MIXTO": "MIXTO",
      "INTERESES": "ASTRONOMIA, FOTOGRAFIA, PAISAJISMO, TREKKING, PLAYA, RIOS, LEVANTAMIENTO DE PESAS",
      "DESCRIPCION_PERSONAL": "SOY ALGUIEN AMABLE, SIMPATICO, ME GUSTA HACER DEPORTE AL AIRE LIBRE, LEO LIBROS Y COSAS ASI",
      "MAXIMA_CAPACIDAD_DE_TU_GRUPO": "4",
      "DEPORTES_EXTREMOS_(SI/NO)": "SI",
      "ACEPTAR_O_RECHAZAR_GRUPO": "NN",
      "FECHA_EN_LA_QUE_VIAJAN": "01/08/2020",
      "CUANTO_TIEMPO_QUIEREN_VIAJAR": "90"
   },
   {
      "NOMBRE":"PAOLA",
      "COMUNA":"PADRE HURTADO",
      "REGION":"METROPOLITANA",
      "FECHA_NACIMIENTO":"1996/05/10",
      "DESDE_DONDE_QUIERE_CONOCER": "11",
      "HASTA_DONDE_QUIERE_CONOCER": "12",
      "SEXO": "F",
      "EL_GRUPO_QUE_QUIERE_SOLO_HOMBRES_MUJERES_O_MIXTO": "MUJERES",
      "RANGO_DE_EDAD_QUE_DESEA_ENCONTRAR_COMPANEROS_MIN": "20",
      "RANGO_DE_EDAD_QUE_DESEA_ENCONTRAR_COMPANEROS_MAX": "30",
      "SOLO_CARPA_HOSTAL_HOTEL_O_MIXTO": "MIXTO",
      "INTERESES": "LECTURA, COMIDA, TREKKING, PLAYA, CAMPING, RIOS",
      "DESCRIPCION_PERSONAL": "ME GUSTA DISFRUTAR DE LA CULTURA Y COMIDAS DE LOS LUGARES A LOS QUE VISITO, HAGO DEPORTE Y LEO BASTANTE",
      "MAXIMA_CAPACIDAD_DE_TU_GRUPO": "2",
      "DEPORTES_EXTREMOS_(SI/NO)": "SI",
      "ACEPTAR_O_RECHAZAR_GRUPO": "NN",
      "FECHA_EN_LA_QUE_VIAJAN": "10/09/2020",
      "CUANTO_TIEMPO_QUIEREN_VIAJAR": "60"
   },
   {
      "NOMBRE":"ROMINA",
      "COMUNA":"LA CISTERNA",
      "REGION":"METROPOLITANA",
      "FECHA_NACIMIENTO":"1993/01/15",
      "DESDE_DONDE_QUIERE_CONOCER": "9",
      "HASTA_DONDE_QUIERE_CONOCER": "13",
      "SEXO": "F",
      "EL_GRUPO_QUE_QUIERE_SOLO_HOMBRES_MUJERES_O_MIXTO": "MIXTO",
      "RANGO_DE_EDAD_QUE_DESEA_ENCONTRAR_COMPANEROS_MIN": "25",
      "RANGO_DE_EDAD_QUE_DESEA_ENCONTRAR_COMPANEROS_MAX": "35",
      "SOLO_CARPA_HOSTAL_HOTEL_O_MIXTO": "MIXTO",
      "INTERESES": "LECTURA, COMIDA, TREKKING, ASTRONOMIA, CAMPING, RIOS, FOTOGRAFIA",
      "DESCRIPCION_PERSONAL": "ME GUSTA DISFRUTAR DE LA CULTURA Y COMIDAS DE LOS LUGARES A LOS QUE VISITO, HAGO DEPORTE Y LEO BASTANTE",
      "MAXIMA_CAPACIDAD_DE_TU_GRUPO": "5",
      "DEPORTES_EXTREMOS_(SI/NO)": "SI",
      "ACEPTAR_O_RECHAZAR_GRUPO": "NN",
      "FECHA_EN_LA_QUE_VIAJAN": "05/07/2020",
      "CUANTO_TIEMPO_QUIEREN_VIAJAR": "120"
   }
]
const userLoad = [
  {
    "NOMBRE":"JOSE",
    "COMUNA":"MAIPU",
    "REGION":"METROPOLITANA",
    "FECHA_NACIMIENTO":"1994/07/07",
    "DESDE_DONDE_QUIERE_CONOCER": "9",
    "HASTA_DONDE_QUIERE_CONOCER": "12",
    "SEXO": "M",
    "EL_GRUPO_QUE_QUIERE_SOLO_HOMBRES_MUJERES_O_MIXTO": "M",
    "RANGO_DE_EDAD_QUE_DESEA_ENCONTRAR_COMPANEROS_MIN": "18",
    "RANGO_DE_EDAD_QUE_DESEA_ENCONTRAR_COMPANEROS_MAX": "30",
    "SOLO_CARPA_HOSTAL_HOTEL_O_MIXTO": "MIXTO",
    "INTERESES": "ASTRONOMIA, FOTOGRAFIA, PAISAJISMO, TREKKING, PLAYA, RIOS, LEVANTAMIENTO DE PESAS",
    "DESCRIPCION_PERSONAL": "SOY ALGUIEN AMABLE, SIMPATICO, ME GUSTA HACER DEPORTE AL AIRE LIBRE, LEO LIBROS Y COSAS ASI",
    "MAXIMA_CAPACIDAD_DE_TU_GRUPO": "4",
    "DEPORTES_EXTREMOS_(SI/NO)": "SI",
    "ACEPTAR_O_RECHAZAR_GRUPO": "NN",
    "FECHA_EN_LA_QUE_VIAJAN": "01/08/2020",
    "CUANTO_TIEMPO_QUIEREN_VIAJAR": "90"
 }
]
const calculateAge = (dateString) => {
  var today = new Date();
  var birthDate = new Date(dateString);
  var age = today.getFullYear() - birthDate.getFullYear();
  var m = today.getMonth() - birthDate.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
      age--;
  }
  return age;
}
class ExecuteMatch extends Component {
  render(){
    return (
      <div>
          <DataStructure data={dataUsers} userLoad={userLoad} calculateAge={calculateAge} />
      </div>
    );
  }
}

export default ExecuteMatch;
